# Generated by Django 3.1.2 on 2020-11-02 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=10)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('image', models.FileField(upload_to='teachers')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.FileField(null=True, upload_to='students'),
        ),
    ]
